version: "3.8"
services:
  mev-boost:
    build:
      context: mev-boost
      args:
        UPSTREAM_VERSION: 1.8
    volumes:
      - data:/var/lib/mev-boost
    environment:
      RELAYS: ""
      EXTRA_OPTS: ""
    restart: unless-stopped
volumes:
  data: {}
