name: "Main"
on:
  pull_request:
  push:
    branches:
      - "master"
      - "main"
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "README.md"

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build test
    if: github.event_name != 'push'
    steps:
      - uses: actions/checkout@v4
      - run: npx @dappnode/dappnodesdk build --skip_save --variant mainnet

  # e2e-test:
  #   runs-on: holesky
  #   needs: build-test
  #   if: github.event_name != 'push'
  #   name: End to end tests
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: npx @dappnode/dappnodesdk@latest github-action test-end-to-end --errorLogsTimeout 120 --healthCheckUrl http://mev-boost.mev-boost-holesky.dappnode:18550 --network holesky
  #       env:
  #         VALIDATOR_INDEX: ${{ secrets.HOLESKY_VALIDATOR_INDEX }}

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: npx @dappnode/dappnodesdk publish minor --dappnode_team_preset --all-variants
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEVELOPER_ADDRESS: "0xf35960302a07022aba880dffaec2fdd64d5bf1c1"
